### ISSUE TITLE
 example to start with

### ISSUE THREAD

**Issue by Abdulaziz-Alqasmi** [lalten/libsocketcan#1]
Hello,
I have read the documentation and I  tried a lot to make my first c code with this library to work but i did not reach anywhere, can someone guide me and provide an example to dump and send can messages with this library.
thanks.

**Comment by lalten** [comment]
Hi @Abdulaziz-Alqasmi, this repository is just a mirror to add online docs. Closing because I assume you've found a solution since 2018!
